apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
helmCharts:
- name: cert-manager
  valuesInline:
    crds:
      enabled: true
  releaseName: cert-manager
  repo: https://charts.jetstack.io
