apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-eks-pod-identity-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://jkroepke.github.io/helm-charts/
    targetRevision: v2.5.2
    chart: amazon-eks-pod-identity-webhook 
    helm:
      valuesObject: 
        replicaCount: 2
        # Require static-worker nodes for pod identity webhook (critical)
        nodeSelector:
          node-type: static-worker
        tolerations:
        - key: node-role.kubernetes.io/static-worker
          operator: Equal
          value: "true"
          effect: NoSchedule
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                  - static-worker
        config:
          stsRegionalEndpoint: true
          defaultAwsRegion: ${AWS_REGION}
          extraArgs:
            - --service-account-lookup-grace-period=2s
        image:
          registry: public.ecr.aws
          repository: eks/amazon-eks-pod-identity-webhook
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /spec/replicas
      kind: Deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m