apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-eks-pod-identity-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  source:
    repoURL: https://jkroepke.github.io/helm-charts/
    # renovate: datasource=helm registryUrl=https://jkroepke.github.io/helm-charts depName=amazon-eks-pod-identity-webhook
    targetRevision: 2.5.5
    chart: amazon-eks-pod-identity-webhook 
    helm:
      valuesObject: 
        replicaCount: 2
        # Require critical addon nodes for pod identity webhook (critical)
        nodeSelector: {node-type: system}
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        affinity:
        config:
          stsRegionalEndpoint: true
          defaultAwsRegion: ${AWS_REGION}
          extraArgs:
            - --service-account-lookup-grace-period=2s
        image:
          registry: public.ecr.aws
          repository: eks/amazon-eks-pod-identity-webhook
        # Use cert-manager for TLS certificates
        # cert-manager installs first (wave 4), then webhook can use it (wave 5)
        pki:
          certManager:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /spec/replicas
      kind: Deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - HealthCheckTimeout=5m
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m