apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/
    chart: aws-ebs-csi-driver
    targetRevision: "*"
    helm:
      valuesObject:
        storageClasses:
          - name: gp3-encrypted
            volumeBindingMode: WaitForFirstConsumer
            parameters:
              type: gp3
              encrypted: "true"
            provisioner: ebs.csi.aws.com
        controller:
          serviceAccount:
            create: true
            name: aws-ebs-csi-driver
            annotations:
              eks.amazonaws.com/role-arn: ${AWS_EBS_CSI_DRIVER_ROLE_ARN}
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3