apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-ebs-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/aws-ebs-csi-driver/
    chart: aws-ebs-csi-driver
    targetRevision: "*"
    helm:
      valuesObject:
        storageClasses:
          - name: gp3-encrypted
            volumeBindingMode: WaitForFirstConsumer
            reclaimPolicy: Delete
            parameters:
              type: gp3
              encrypted: "true"
            provisioner: ebs.csi.aws.com
        controller:
          # Require critical addon nodes for EBS CSI controller (critical)
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          affinity:
          resources:
            requests:
              cpu: 10m
              memory: 75Mi
            limits:
              cpu: 100m
              memory: 150Mi
          serviceAccount:
            create: true
            name: aws-ebs-csi-driver
            annotations:
              eks.amazonaws.com/role-arn: ${AWS_EBS_CSI_DRIVER_ROLE_ARN}
        node:
          # Node DaemonSet should run on all nodes, no preference needed
          resources:
            requests:
              cpu: 10m
              memory: 43Mi
            limits:
              cpu: 100m
              memory: 86Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3