apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        
        # ServiceAccount configuration with IRSA
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: ${CERT_MANAGER_ROLE_ARN}
            
        # Node affinity - Run only on critical addon nodes
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
            
        resources:
          requests:
            cpu: 5m
            memory: 25Mi
          limits:
            cpu: 50m
            memory: 80Mi
            
        # Configure cainjector with the same node affinity
        cainjector:
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          resources:
            requests:
              cpu: 5m
              memory: 58Mi
            limits:
              cpu: 50m
              memory: 116Mi
              
        # Configure webhook with the same node affinity
        webhook:
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          resources:
            requests:
              cpu: 5m
              memory: 20Mi
            limits:
              cpu: 50m
              memory: 40Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /spec/replicas
      kind: Deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
