apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        
        # ServiceAccount configuration with IRSA
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            eks.amazonaws.com/role-arn: ${CERT_MANAGER_ROLE_ARN}
            
        # Node affinity - Run only on static-worker nodes
        nodeSelector:
          node-type: static-worker
        tolerations:
        - key: node-role.kubernetes.io/static-worker
          operator: Equal
          value: "true"
          effect: NoSchedule
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-type
                  operator: In
                  values:
                  - static-worker
            
        resources:
          requests:
            cpu: 5m
            memory: 25Mi
          limits:
            cpu: 50m
            memory: 50Mi
            
        # Configure cainjector with the same node affinity
        cainjector:
          nodeSelector:
            node-type: static-worker
          tolerations:
          - key: node-role.kubernetes.io/static-worker
            operator: Equal
            value: "true"
            effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                    - static-worker
          resources:
            requests:
              cpu: 5m
              memory: 35Mi
            limits:
              cpu: 50m
              memory: 70Mi
              
        # Configure webhook with the same node affinity
        webhook:
          nodeSelector:
            node-type: static-worker
          tolerations:
          - key: node-role.kubernetes.io/static-worker
            operator: Equal
            value: "true"
            effect: NoSchedule
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-type
                    operator: In
                    values:
                    - static-worker
          resources:
            requests:
              cpu: 5m
              memory: 11Mi
            limits:
              cpu: 50m
              memory: 22Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /spec/replicas
      kind: Deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
