apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    targetRevision: v1.18.2
    chart: cert-manager
    helm:
      valuesObject:
        crds:
          enabled: true
        resources:
          requests:
            cpu: 5m
            memory: 25Mi
          limits:
            cpu: 50m
            memory: 50Mi
        cainjector:
          resources:
            requests:
              cpu: 5m
              memory: 35Mi
            limits:
              cpu: 50m
              memory: 70Mi
        webhook:
          resources:
            requests:
              cpu: 5m
              memory: 11Mi
            limits:
              cpu: 50m
              memory: 22Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  ignoreDifferences:
    - group: apps
      jsonPointers:
        - /spec/replicas
      kind: Deployment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
