apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: oci://public.ecr.aws/karpenter/karpenter
    targetRevision: 1.6.3
    path: .
    helm:
      valuesObject:
        # Replica count for high availability
        replicas: 2
        
        # Service account configuration with IRSA
        serviceAccount:
          create: true
          name: karpenter
          annotations:
            eks.amazonaws.com/role-arn: ${KARPENTER_ROLE_ARN}
        
        # Webhook configuration
        webhook:
          enabled: true
          port: 8443
        
        # Logging configuration
        logLevel: info
        
        # Node affinity and tolerations
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: karpenter.sh/provisioner-name
                  operator: DoesNotExist
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                    - karpenter
                topologyKey: kubernetes.io/hostname
        
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        
        # Security configuration
        securityContext:
          fsGroup: 65532
        
        # Additional settings for production
        dnsPolicy: Default
        dnsConfig:
          options:
          - name: ndots
            value: "1"
        
        # Metrics and monitoring
        serviceMonitor:
          enabled: false
          additionalLabels:
            release: prometheus-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: karpenter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m