apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    # renovate: datasource=helm registryUrl=https://prometheus-community.github.io/helm-charts depName=kube-prometheus-stack
    targetRevision: 78.2.0
    helm:
      valuesObject:
        prometheus:
          prometheusSpec:
            # Run on system nodes (critical component)
            nodeSelector:
              node-type: system
            tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
            affinity:
            resources:
              requests:
                cpu: 15m
                memory: 341Mi
              limits:
                cpu: 200m
                memory: 682Mi
        grafana:
          # Run on system nodes (critical component)
          nodeSelector:
            node-type: system
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          affinity:
          resources:
            requests:
              cpu: 10m
              memory: 367Mi
            limits:
              cpu: 100m
              memory: 734Mi
        prometheusOperator:
          # Run on system nodes (critical component)
          nodeSelector:
            node-type: system
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          affinity:
          resources:
            requests:
              cpu: 5m
              memory: 25Mi
            limits:
              cpu: 50m
              memory: 50Mi
        kubeStateMetrics:
          # Run on system nodes (critical component)
          nodeSelector:
            node-type: system
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          affinity:
          resources:
            requests:
              cpu: 5m
              memory: 19Mi
            limits:
              cpu: 50m
              memory: 38Mi
        nodeExporter:
          # NodeExporter should run on all nodes (DaemonSet), no node preference needed
          resources:
            requests:
              cpu: 5m
              memory: 12Mi
            limits:
              cpu: 50m
              memory: 24Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
