apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: kyverno
    repoURL: https://kyverno.github.io/kyverno
    targetRevision: 3.5.1
    helm:
      valuesObject:
        admissionController:
          replicas: 2
          # Run admission controller on system nodes (critical component)
          nodeSelector:
            node-type: system
          tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
          # Ensure admission controller pods are distributed across availability zones for high availability
          topologySpreadConstraints:
          - maxSkew: 1
            topologyKey: topology.kubernetes.io/zone
            whenUnsatisfiable: DoNotSchedule
            labelSelector:
              matchLabels:
                app.kubernetes.io/component: admission-controller
        
        # Run background controllers on Karpenter-managed nodes
        backgroundController:
          nodeSelector:
            node-type: karpenter-managed
        cleanupController:
          nodeSelector:
            node-type: karpenter-managed
        reportsController:
          nodeSelector:
            node-type: karpenter-managed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true