---
apiVersion: v1
kind: Namespace
metadata:
  name: hsp-addons
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hsp-addons
  namespace: hsp-addons
  labels:
    cache.kyverno.io/enabled: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "20"
data:
  accountId: |
    ${AWS_ACCOUNT_ID}
  sharedServicesAccountId: |
    ${SHARED_SERVICES_ACCOUNT_ID}
  region: ${AWS_REGION}
  partition: ${AWS_PARTITION}
  enabledPullThroughRegistries: |
    ["docker-hub","quay","github","k8s","ecr-public"]
  eks: |
    {
      "oidcProviderArn": "${OIDC_PROVIDER_ARN}",
      "oidcProvider": "${OIDC_PROVIDER}",
      "clusterName": "${CLUSTER_NAME}",
      "clusterId": "${CLUSTER_NAME}",
      "resourcePrefix": "${RESOURCE_PREFIX}",
      "clusterFqdn": "${CLUSTER_FQDN}",
      "clusterEndpoint": "${CLUSTER_ENDPOINT}"
    }
  servicesVpc: |
    {
      "id": "${AWS_VPC_ID}",
      "privateSubnetIds": ${AWS_PRIVATE_SUBNET_IDS},
      "subnetGroups": {
        "database": ${AWS_RDS_SUBNET_GROUP},
        "redshift": ${AWS_REDSHIFT_SUBNET_GROUP},
        "elasticache": ${AWS_ELASTICACHE_SUBNET_GROUP}
      },
      "securityGroups": {
        "database": ${AWS_RDS_SECURITY_GROUPS},
        "redshift": ${AWS_REDSHIFT_SECURITY_GROUPS},
        "elasticache": ${AWS_ELASTICACHE_SECURITY_GROUPS},
        "activemq": ${AWS_ACTIVEMQ_SECURITY_GROUPS}
      }
    }
  tags: |
    {
      "Environment": "${RESOURCE_PREFIX}"
    }
