apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kyverno-app.yaml
  - kyverno-aws-lbc-pod-identity-policy.yaml
  - kyverno-cert-manager-pod-identity-policy.yaml
  - kyverno-karpenter-pod-identity-policy.yaml
  - kyverno-ebs-csi-controller-pod-identity-policy.yaml
  - kyverno-external-dns-pod-identity-policy.yaml  