apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/external-dns/
    chart: external-dns
    # renovate: datasource=helm registryUrl=https://kubernetes-sigs.github.io/external-dns depName=external-dns
    targetRevision: 1.20.0
    helm:
      valuesObject:
        sources:
          - service
          - ingress
          - gateway-httproute
        # Require critical addon nodes for external-dns (critical)
        nodeSelector:
          node-type: system
        tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        affinity:
        resources:
          limits:
            memory: 64Mi
          requests:
            cpu: 20m
            memory: 32Mi
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            eks.amazonaws.com/role-arn: ${AWS_EXTERNAL_DNS_ROLE_ARN}
        domainFilters:
          - ${CLUSTER_FQDN}
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 3