apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: ecr-pull-through
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Pod
spec:
  background: false
  mutateExistingOnPolicyUpdate: false
  rules:
    - name: mutate-dockerhub-images
      context:
        - name: aws
          configMap:
            name: hsp-addons
            namespace: hsp-addons
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{ request.operation || 'BACKGROUND' }}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}"
            operator: NotEqual
            value: ""
          - key: docker-hub
            operator: AnyIn
            value: "{{ aws.data.enabledPullThroughRegistries }}"
      mutate:
        foreach:
          - list: "request.object.spec.initContainers[]"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(?:docker\\.io/)?([^\\.\\.W]*)/(.*)$', regex_replace_all('^(?:docker\\.io/)?([^:\\W/]*)(:.*)?$', '{{element.image}}', 'library/$1$2' ), '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/docker-hub/$1/$2' ) }}"
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(?:docker\\.io/)?([^\\.\\.W]*)/(.*)$', regex_replace_all('^(?:docker\\.io/)?([^:\\W/]*)(:.*)?$', '{{element.image}}', 'library/$1$2' ), '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/docker-hub/$1/$2' ) }}"
          - list: "request.object.spec.ephemeralContainers[]"
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(?:docker\\.io/)?([^\\.\\.W]*)/(.*)$', regex_replace_all('^(?:docker\\.io/)?([^:\\W/]*)(:.*)?$', '{{element.image}}', 'library/$1$2' ), '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/docker-hub/$1/$2' ) }}"
    - name: mutate-quay-images
      context:
        - name: aws
          configMap:
            name: hsp-addons
            namespace: hsp-addons
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}"
            operator: NotEqual
            value: ""
          - key: quay
            operator: AnyIn
            value: "{{ aws.data.enabledPullThroughRegistries }}"
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(quay\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/quay/$2' ) }}"
          - list: "request.object.spec.initContainers[]"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(quay\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/quay/$2' ) }}"
          - list: "request.object.spec.ephemeralContainers[]"
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(quay\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/quay/$2' ) }}"
    - name: mutate-github-images
      context:
        - name: aws
          configMap:
            name: hsp-addons
            namespace: hsp-addons
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}"
            operator: NotEqual
            value: ""
          - key: github
            operator: AnyIn
            value: "{{ aws.data.enabledPullThroughRegistries }}"
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(ghcr\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/github/$2' ) }}"
          - list: "request.object.spec.initContainers[]"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(ghcr\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/github/$2' ) }}"
          - list: "request.object.spec.ephemeralContainers[]"
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(ghcr\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/github/$2' ) }}"
    - name: mutate-k8s-images
      context:
        - name: aws
          configMap:
            name: hsp-addons
            namespace: hsp-addons
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}"
            operator: NotEqual
            value: ""
          - key: k8s
            operator: AnyIn
            value: "{{ aws.data.enabledPullThroughRegistries }}"
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(registry\\.k8s\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/k8s/$2' ) }}"
          - list: "request.object.spec.initContainers[]"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(registry\\.k8s\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/k8s/$2' ) }}"
          - list: "request.object.spec.ephemeralContainers[]"
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(registry\\.k8s\\.io/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/k8s/$2' ) }}"
    - name: mutate-ecr-public-images
      context:
        - name: aws
          configMap:
            name: hsp-addons
            namespace: hsp-addons
      match:
        any:
          - resources:
              kinds:
                - Pod
      preconditions:
        all:
          - key: "{{request.operation || 'BACKGROUND'}}"
            operator: AnyIn
            value:
              - CREATE
              - UPDATE
          - key: "{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}"
            operator: NotEqual
            value: ""
          - key: ecr-public
            operator: AnyIn
            value: "{{ aws.data.enabledPullThroughRegistries }}"
      mutate:
        foreach:
          - list: "request.object.spec.containers[]"
            patchStrategicMerge:
              spec:
                containers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(public\\.ecr\\.aws/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/ecr-public/$2' ) }}"
          - list: "request.object.spec.initContainers[]"
            patchStrategicMerge:
              spec:
                initContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(public\\.ecr\\.aws/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/ecr-public/$2' ) }}"
          - list: "request.object.spec.ephemeralContainers[]"
            patchStrategicMerge:
              spec:
                ephemeralContainers:
                  - name: "{{ element.name }}"
                    image: "{{ regex_replace_all('^(public\\.ecr\\.aws/)(.*)$', '{{element.image}}', '{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.sharedServicesAccountId }}', '') }}.dkr.ecr.{{ regex_replace_all('^\\s+|\\s+$', '{{ aws.data.region }}', '') }}.amazonaws.com/ecr-public/$2' ) }}"
