apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.crossplane.io/stable
    chart: crossplane
    # renovate: datasource=github-releases depName=crossplane/crossplane
    targetRevision: v2.1.3
    helm:
      valuesObject:
        image:
          repository: ghcr.io/crossplane/crossplane
        args:
          - --enable-operations
        metrics:
          enabled: true
        resources:
          requests:
            cpu: 10m
            memory: 512Mi
          limits:
            cpu: 100m
            memory: 1Gi
        
        # Schedule on system nodes like ArgoCD (critical addon)
        nodeSelector:
          node-type: system
        tolerations:
          - key: CriticalAddonsOnly
            operator: Exists
        
        # rbacManager is also critical - schedule on system nodes
        rbacManager:
          nodeSelector:
            node-type: system
          tolerations:
            - key: CriticalAddonsOnly
              operator: Exists
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
