apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: provider-kubernetes
  annotations:
   "argocd.argoproj.io/sync-wave": "20"
spec:
  serviceAccountTemplate:
    metadata:
      name: provider-kubernetes
