apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: obs-eu-dev-wildcard
  namespace: gateway
  annotations:
    argocd.argoproj.io/sync-wave: "6"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretName: obs-eu-dev-wildcard-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "*.obs-eu-dev.hsp.philips.com"
    - "obs-eu-dev.hsp.philips.com"
