apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata: 
  name: ${RESOURCE_PREFIX}-eso
  namespace: external-secrets
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "${OIDC_PROVIDER_ARN}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "${OIDC_PROVIDER}:aud": "sts.amazonaws.com",
                    "${OIDC_PROVIDER}:sub": "system:serviceaccount:external-secrets:external-secrets"
                }
            }
          }
        ]
      }
    description: "IRSA Role for External Secrets Operator"
    maxSessionDuration: 3600