apiVersion: iam.aws.upbound.io/v1beta1
kind: Role
metadata: 
  name: ${RESOURCE_PREFIX}-externals-secrets-role
  namespace: external-secrets
spec:
  forProvider:
    assumeRolePolicy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "Federated": "${OIDC_PROVIDER_ARN}"
            },
            "Action": "sts:AssumeRoleWithWebIdentity",
            "Condition": {
                "StringLike": {
                    "${OIDC_PROVIDER}:aud": "sts.amazonaws.com",
                    "${OIDC_PROVIDER}:sub": "system:serviceaccount:external-secrets:external-secrets"
                }
            }
          }
        ]
      }
    managedPolicyArns:
      - arn:aws:iam::aws:policy/SecretsManagerReadWrite
      - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess 